version: '3.9'


services:
web:
build: .
command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --workers 3 --log-file -
volumes:
- .:/app
ports:
- "8000:8000"
env_file:
- .env
depends_on:
- db


db:
image: postgres:15
restart: always
environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: mysite
ports:
- "5432:5432"
volumes:
- postgres_data:/var/lib/postgresql/data


volumes:
postgres_data: