version: '3.9'

services:
  web:
    build: .
    # For development we run the Django dev server with volumes (fast edit cycle)
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"  # dev only — allows local DB clients to connect
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
